var muvek = {
  'irasok/osszes-proza.html#humanizmus':'Humanizmus',
  'versek/osszes-vers.html#a-banat':'A bánat',
  'versek/osszes-vers.html#a-batrak':'A bátrak',
  'versek/osszes-vers.html#a-betuk-sivatagaban':'A betűk sivatagában',
  'versek/osszes-vers.html#a-boldogsag-nyitott-konyv':'A boldogság nyitott könyv, tessék, olvassák',
  'versek/osszes-vers.html#a-bor-alatt-halovany-arnyek':'A bőr alatt halovány árnyék',
  'versek/osszes-vers.html#a-bun':'A bűn',
  'versek/osszes-vers.html#a-bun-valt':'A bűn (Változat)',
  'versek/osszes-vers.html#a-cipo':'A cipő',
  'versek/osszes-vers.html#a-csapat':'A csapat',
  'versek/osszes-vers.html#a-csillam-szemembol-kihagy':'(A csillám szememből kihagy … )',
  'versek/osszes-vers.html#a-csipogo-arnyakbol':'(A csipogó árnyakból … )',
  'versek/osszes-vers.html#egy-toredek-alakulasa-valt':'(A csipogó árnyakból … ) (Változatok)',
  'versek/osszes-vers.html#a-csoda':'A csoda',
  'versek/osszes-vers.html#a-csodaszarvas':'A csodaszarvas',
  'versek/osszes-vers.html#a-dunanal':'A Dunánál',
  'versek/osszes-vers.html#a-fakon':'(A fákon … )',
  'versek/osszes-vers.html#a-fan-a-levelek':'A fán a levelek …',
  'versek/osszes-vers.html#osz-valt':'(A fán a levelek … ) (Változat)',
  'versek/osszes-vers.html#a-fergeteg-orman':'A fergetek ormán',
  'versek/osszes-vers.html#a-fust':'A füst',
  'versek/osszes-vers.html#a-gondolkodo-szonettje':'A gondolkodó szonettje',
  'versek/osszes-vers.html#a-gyerekszemu-elet-tavon':'A gyerekszemű élet-tavon',
  'versek/osszes-vers.html#a-halalrol':'A halálról',
  'versek/osszes-vers.html#a-hallgatag-gep':'(A hallgatag gép … )',
  'versek/osszes-vers.html#a-harisnyaja-egy-lucsok':'(A harisnyája egy lucsok … )',
  'versek/osszes-vers.html#a-harom-kovacs':'A három kovács',
  'versek/osszes-vers.html#a-hetedik':'A hetedik',
  'versek/osszes-vers.html#a-hit-boldogit':'A hit boldogít',
  'versek/osszes-vers.html#a-hullamok-lagy-tanca':'(A hullámok lágy tánca … )',
  'versek/osszes-vers.html#a-jambor-tehen':'A jámbor tehén',
  'versek/osszes-vers.html#a-kanasz':'A kanász',
  'versek/osszes-vers.html#a-kelo-korongba-hajitom':'(A kelő korongba hajítom … )',
  'versek/osszes-vers.html#a-kerten':'(A kerten … )',
  'versek/osszes-vers.html#a-kesei-sirato-vazlataibol-valt':'[A „Kései sirató” vázlataiból]]',
  'versek/osszes-vers.html#a-kinhoz-kotnek-kemeny-kotelek-tor':'(A kínhoz kötnek kemény kötelek … )',
  'versek/osszes-vers.html#a-kozmosz-eneke':'A Kozmosz éneke',
  'versek/osszes-vers.html#a-kovezeten':'(A kövezeten … )',
  'versek/osszes-vers.html#a-kutya':'A kutya',
  'versek/osszes-vers.html#a-legutolso-harcos':'A legutolsó harcos',
  'versek/osszes-vers.html#a-legutolso-harcos-valt':'A legutolsó harcos (Változat)',
  'versek/osszes-vers.html#a-lovak':'(A lovak … )',
  'versek/osszes-vers.html#a-mennyei-pancelvonat':'A mennyei páncélvonat',
  'versek/osszes-vers.html#a-multkor-szerda-este':'(A multkor, szerda este … )',
  'versek/osszes-vers.html#a-nagy-varosokat':'A nagy városokat',
  'versek/osszes-vers.html#a-noi-sziv':'A női szív',
  'versek/osszes-vers.html#a-nyakaba-kek-koto':'(A nyakába kék kötő … )',
  'versek/osszes-vers.html#a-nyarfak-kozt':'(A nyárfák közt … )',
  'versek/osszes-vers.html#a-pap-mosolyog-valt':'A pap mosolyog',
  'versek/osszes-vers.html#a-paradicsom-elette-lesz':'A paradicsom életté lesz',
  'versek/osszes-vers.html#a-pipafust-lenyul-a-foldig':'(A pipafüst lenyúl a földig … )',
  'versek/osszes-vers.html#a-rak':'A rák',
  'versek/osszes-vers.html#a-royalban-muzsika':'(A Royalban muzsika … )',
  'versek/osszes-vers.html#a-spenot':'A spenót',
  'versek/osszes-vers.html#a-szamokrol':'A számokról',
  'versek/osszes-vers.html#a-szemed':'A szemed',
  'versek/osszes-vers.html#a-szent-jobb-unnepen':'A Szent Jobb ünnepén',
  'versek/osszes-vers.html#a-szerelmes-szonettje':'A szerelmes szonettje',
  'versek/osszes-vers.html#a-szeretok-hallgatva-alltak':'(A szeretők hallgatva álltak … )',
  'versek/osszes-vers.html#a-szigeten':'A szigeten',
  'versek/osszes-vers.html#a-sziv-s-a-szem':'A szív s a szem',
  'versek/osszes-vers.html#a-szolnoki-hidon':'A szolnoki hídon',
  'versek/osszes-vers.html#a-tavi-torony-harangozoja':'A tavi torony harangozója',
  'versek/osszes-vers.html#a-tavol-uj-s-uj-egeket-szor-valt':'A távol új s új egeket szór',
  'versek/osszes-vers.html#a-to-jeget':'(A tó jegét … )',
  'versek/osszes-vers.html#a-tokesek-hasznarol-valt':'A tőkések hasznáról',
  'versek/osszes-vers.html#a-varos-peremen':'A város peremén',
  'versek/osszes-vers.html#a-vasarteren':'(A vásártéren … )',
  'versek/osszes-vers.html#a-vergodo-diak':'A vergődő diák',
  'versek/osszes-vers.html#a-vilag-ha-elbujdostat':'A világ ha elbujdostat',
  'versek/osszes-vers.html#a-vilag-megteremtese':'A világ megteremtése',
  'versek/osszes-vers.html#acelgomb-fol-fol-emelkedj':'Acélgömb föl, föl! Emelkedj!',
  'versek/osszes-vers.html#ad-sidera':'Ad sidera …',
  'versek/osszes-vers.html#ady-emlekezete':'Ady emlékezete',
  'versek/osszes-vers.html#ady-endre-helyett-mondom':'Ady Endre helyett mondom',
  'versek/osszes-vers.html#ahol-a-szabadsag-a-rend':'(Ahol a szabadság a rend … )',
  'versek/osszes-vers.html#ajandek':'Ajándék',
  'versek/osszes-vers.html#ajtot-nyitok':'Ajtót nyitok',
  'versek/osszes-vers.html#akacokhoz':'Ákácokhoz',
  'versek/osszes-vers.html#aki-szegeny-az-a-legszegenyebb':'Aki szegény, az a legszegényebb',
  'versek/osszes-vers.html#aki-szeretni-gyava-vagy':'… aki szeretni gyáva vagy',
  'versek/osszes-vers.html#akkor':'Akkor',
  'versek/osszes-vers.html#aldalak-buval-vigalommal':'Áldalak búval, vigalommal',
  'versek/osszes-vers.html#aldott-legy-jo-magyarorszag':'Áldott légy, jó Magyarország!',
  'versek/osszes-vers.html#alkalmi-vers-a-szocializmus-allasarol':'Alkalmi vers a szocializmus állásáról',
  'versek/osszes-vers.html#alkohol':'Alkohol',
  'versek/osszes-vers.html#allas-nelkul-elek':'(Állás nélkül élek … )',
  'versek/osszes-vers.html#allegorie':'Allégorie',
  'versek/osszes-vers.html#alomban-enyem-vagy':'Álomban enyém vagy',
  'versek/osszes-vers.html#altato':'Altató',
  'versek/osszes-vers.html#aludj':'(Aludj … )',
  'versek/osszes-vers.html#am-fenn-a-magas-eszakon':'(… ám fenn a magas északon … )',
  'versek/osszes-vers.html#keltezetlen-toredekek':'(Amikor verset ír az ember … )',
  'versek/osszes-vers.html#amiota':'Amióta …',
  'versek/osszes-vers.html#amit-szivedbe-rejtesz':'Amit szivedbe rejtesz',
  'versek/osszes-vers.html#anya':'Anya',
  'versek/osszes-vers.html#anyam-a-mosasban-gyaszkoszoru':'Anyám a mosásban gyászkoszorú',
  'versek/osszes-vers.html#anyam-meghalt':'(Anyám meghalt … )',
  'versek/osszes-vers.html#anyam':'Anyám',
  'versek/osszes-vers.html#apam-es-anyam':'Apám és anyám',
  'versek/osszes-vers.html#aprilis-11':'Április 11',
  'versek/osszes-vers.html#aradat-valt':'Áradat',
  'versek/osszes-vers.html#arany-kalasztol':'(Arany kalásztól … )',
  'versek/osszes-vers.html#arany':'Arany',
  'versek/osszes-vers.html#aranybojtu':'Aranybojtú',
  'versek/osszes-vers.html#aratas-elott':'Aratás előtt',
  'versek/osszes-vers.html#aratasban':'Aratásban',
  'versek/osszes-vers.html#judit-versek-toredekei':'(Arcodon könnyed ott ragadt … )',
  'versek/osszes-vers.html#arcuk-egy-egy-kis-kulvaros':'(Arcuk egy-egy kis külváros … )',
  'versek/osszes-vers.html#ars-poetica':'Ars poetica',
  'versek/osszes-vers.html#ars-poetica-valt':'Ars poetica (Változat)',
  'versek/osszes-vers.html#asszonyvaras-asszonyszobor-mellett':'Asszonyvárás asszonyszobor mellett',
  'versek/osszes-vers.html#atizzadt-fekvo-helyeden':'(Átizzadt fekvő helyeden … )',
  'versek/osszes-vers.html#axioma':'Axióma',
  'versek/osszes-vers.html#az-en-ki-emberkent-vazlata-valt':'[Az „Én, ki emberként …” vázlata]',
  'versek/osszes-vers.html#az-eszmelet-elozmenyei':'[Az „Eszmélet” előzményei]',
  'versek/osszes-vers.html#az-a-szep-regi-asszony':'Az a szép, régi asszony',
  'versek/osszes-vers.html#az-arnyekok':'Az árnyékok …',
  'versek/osszes-vers.html#az-edesanyjanak':'Az Édesanyjának',
  'versek/osszes-vers.html#az-en-szivem-sokat-csatangolt':'(Az én szivem sokat csatangolt … )',
  'versek/osszes-vers.html#az-isten-itt-allt-a-hatam-mogott':'(Az Isten itt állt a hátam mögött … )',
  'versek/osszes-vers.html#az-oktato-mama-oktatasa':'Az oktató mama oktatása',
  'versek/osszes-vers.html#az-oroszlan-idezese':'Az oroszlán idézése',
  'versek/osszes-vers.html#az-oroszlan-megtorli-orrat':'(Az oroszlán megtörli orrát … )',
  'versek/osszes-vers.html#az-orok-elmulas':'Az örök elmulás',
  'versek/osszes-vers.html#az-orok-polyphemos':'Az örök Polyphemos',
  'versek/osszes-vers.html#az-orult-hajotorott':'Az őrült hajótörött',
  'versek/osszes-vers.html#az-uj-honorhoz':'Az új honőrhöz!',
  'versek/osszes-vers.html#azt-mondjak':'Azt mondják',
  'versek/osszes-vers.html#azt-mondjak-valt':'Azt mondják (Változat)',
  'versek/osszes-vers.html#azt-olvastam-hogy-perli-a-nepet':'(Azt olvastam, hogy perli a Nepet … )',
  'versek/osszes-vers.html#baal':'Baál',
  'versek/osszes-vers.html#balatonszarszo':'Balatonszárszó',
  'versek/osszes-vers.html#balga-kolto':'Balga költő',
  'versek/osszes-vers.html#ballada':'Ballada',
  'versek/osszes-vers.html#balogh-joskanak':'(Balogh Jóskának … )',
  'versek/osszes-vers.html#banat-futtam-mint-a-szarvasok':'Bánat (Futtam, mint a szarvasok … )',
  'versek/osszes-vers.html#banat-hat-kijottem-ide':'Bánat (Hát kijöttem ide … )',
  'versek/osszes-vers.html#bermunkas-ballada':'Bérmunkás-ballada',
  'versek/osszes-vers.html#bertalan':'Bertalan',
  'versek/osszes-vers.html#beszel-a-tej':'Beszél a tej',
  'versek/osszes-vers.html#beteg-vagyok':'(Beteg vagyok … )',
  'versek/osszes-vers.html#bethlen-istvan':'Bethlen István',
  'versek/osszes-vers.html#betlehem':'Betlehem',
  'versek/osszes-vers.html#betlehemi-kiralyok':'Betlehemi királyok',
  'versek/osszes-vers.html#bevezeto':'Bevezető',
  'versek/osszes-vers.html#bibliai':'[Bibliai]',
  'versek/osszes-vers.html#biztato-csomagodat-ne-bontsd-ki':'Biztató (Csomagodat ne bontsd ki … )',
  'versek/osszes-vers.html#biztato-kinaban-log-a-mandarin':'Biztató (Kínában lóg a mandarin … )',
  'versek/osszes-vers.html#bocsassatok-meg-baratsag':'(Bocsássátok meg, barátság … )',
  'versek/osszes-vers.html#boldog-hazug':'Boldog hazug …',
  'versek/osszes-vers.html#bolyongok':'Bolyongok',
  'versek/osszes-vers.html#boros-keseruseg':'Boros keserűség',
  'versek/osszes-vers.html#boruljatok-csak-ossze':'(Boruljatok csak össze … )',
  'versek/osszes-vers.html#bosszusag':'Bosszúság',
  'versek/osszes-vers.html#bodulj-torony':'Bődülj torony',
  'versek/osszes-vers.html#braun-evanak':'[Braun Évának]',
  'versek/osszes-vers.html#bukj-fol-az-arbol':'Bukj föl az árból',
  'versek/osszes-vers.html#bus-enekhivas':'Bús énekhivás',
  'versek/osszes-vers.html#bus-magyar-eneke':'Bús magyar éneke',
  'versek/osszes-vers.html#buza':'Buza',
  'versek/osszes-vers.html#buzgosag':'Buzgóság',
  'versek/osszes-vers.html#chant-de-proletaire':'Chant de prolétaire',
  'versek/osszes-vers.html#csak-a-tenger-jott-el':'Csak a tenger jött el',
  'versek/osszes-vers.html#csak-az-olvassa':'(Csak az olvassa … )',
  'versek/osszes-vers.html#csak-most':'(Csak most … )',
  'versek/osszes-vers.html#csend':'Csend',
  'versek/osszes-vers.html#csendes-kevebe-kotott-reggel':'(Csendes, kévébe kötött reggel … )',
  'versek/osszes-vers.html#csengo':'Csengő',
  'versek/osszes-vers.html#csin-bin':'Csin-bin',
  'versek/osszes-vers.html#csodalkozo-bogarak-kozt':'(Csodálkozó bogarak közt … )',
  'versek/osszes-vers.html#csokkeres-tavasszal':'Csókkérés tavasszal',
  'versek/osszes-vers.html#csokol-attila':'(Csókol Attila … )',
  'versek/osszes-vers.html#csokolj-csokolj':'Csókolj, csókolj …',
  'versek/osszes-vers.html#csondes-esteli-zsoltar':'Csöndes estéli zsoltár',
  'versek/osszes-vers.html#csudalkozunk-az-eleten':'Csudálkozunk az életen',
  'versek/osszes-vers.html#csungoje-voltam':'Csüngője voltam',
  'versek/osszes-vers.html#dagadt-hentes-bardja':'(Dagadt hentes bárdja … )',
  'versek/osszes-vers.html#dal':'Dal',
  'versek/osszes-vers.html#dal-valt':'Dal (Változat)',
  'versek/osszes-vers.html#dalocska':'Dalocska',
  'versek/osszes-vers.html#kedves-joco':'(De szeretnék gazdag lenni … )',
  'versek/osszes-vers.html#derengo-rozsa':'Derengő rózsa',
  'versek/osszes-vers.html#dicsertessek':'Dícsértessék',
  'versek/osszes-vers.html#divanyon-fekszem':'(Diványon fekszem … )',
  'versek/osszes-vers.html#dormogo':'Dörmögő',
  'versek/osszes-vers.html#draga-barataim':'(Drága barátaim … )',
  'versek/osszes-vers.html#dudolo':'Dúdoló',
  'versek/osszes-vers.html#du-feu':'(Du feu … )',
  'versek/osszes-vers.html#edesanyam-egyetlen-draga':'(Édesanyám, egyetlen, drága … )',
  'versek/osszes-vers.html#egeres':'Egeres',
  'versek/osszes-vers.html#egesz-testeben-reszket':'(Egész testében reszket … )',
  'versek/osszes-vers.html#egy-asszony-s-egy-leany':'Egy asszony s egy leány',
  'versek/osszes-vers.html#egy-asszony-s-egy-leany-valt':'Egy asszony s egy leány (Változat)',
  'versek/osszes-vers.html#egy-buntetotorvenyszeki-targyalas-irataibol':'Egy büntetőtörvényszéki tárgyalás irataiból',
  'versek/osszes-vers.html#egy-ifju-parra':'Egy ifju párra',
  'versek/osszes-vers.html#egy-kisgyerek-sir':'Egy kisgyerek sír',
  'versek/osszes-vers.html#egy-koltore-sakalt-kialt':'Egy költőre (Sakált kiált … )',
  'versek/osszes-vers.html#egy-koltore-teged-szeretnek':'Egy költőre (Téged szeretnek … )',
  'versek/osszes-vers.html#egy-spanyol-foldmives-sirverse':'Egy spanyol földmíves sírverse',
  'versek/osszes-vers.html#egy-toredek-alakulasa-valt':'[Egy töredék alakulása]',
  'versek/osszes-vers.html#egy-vak-ember-sir':'Egy vak ember sír',
  'versek/osszes-vers.html#egyedul':'Egyedül',
  'versek/osszes-vers.html#eggyeolelodes-vagya':'Eggyéölelődés vágya',
  'versek/osszes-vers.html#egyszeru-ez':'Egyszerű ez',
  'versek/osszes-vers.html#egyszeru-vers':'Egyszerű vers',
  'versek/osszes-vers.html#egyugyu-enek':'Együgyü ének',
  'versek/osszes-vers.html#ehseg':'Éhség',
  'versek/osszes-vers.html#ket-dal':'Éji dal',
  'versek/osszes-vers.html#ejjel':'Éjjel',
  'versek/osszes-vers.html#ekrazittomeg':'Ekrazittömeg',
  'versek/osszes-vers.html#el-innen':'El innen',
  'versek/osszes-vers.html#elegia':'Elégia',
  'versek/osszes-vers.html#elkoszono-szelid-szavak':'Elköszönő szelíd szavak',
  'versek/osszes-vers.html#toredekes-rogtonzesek-tormeleksorok':'(Elküldtem hozzád Sándor Imrét … )',
  'versek/osszes-vers.html#elmaradt-oleles-miatt':'Elmaradt ölelés miatt',
  'versek/osszes-vers.html#eltem-igy-erdemeltem-en-meg':'(Éltem, így érdemeltem én meg … )',
  'versek/osszes-vers.html#ember-is-magyar-is-magam-is':'Ember is; magyar is; magam is',
  'versek/osszes-vers.html#ember-ne-felj':'(Ember, ne félj … )',
  'versek/osszes-vers.html#emberek':'Emberek',
  'versek/osszes-vers.html#emberiseg':'Emberiség',
  'versek/osszes-vers.html#emlek':'Emlék',
  'versek/osszes-vers.html#en-azt-akarom-bar-ostobanak-latszik':'(Én azt akarom, bár ostobának látszik … )',
  'versek/osszes-vers.html#en-dobtam':'Én dobtam',
  'versek/osszes-vers.html#en-hazam-fajom-es-emberisegem':'(Én hazám, fajom és emberiségem … )',
  'versek/osszes-vers.html#en-nem-tudom':'Én nem tudom …',
  'versek/osszes-vers.html#en-nem-tudtam':'Én nem tudtam',
  'versek/osszes-vers.html#en-ki-emberkent':'(Én, ki emberként … )',
  'versek/osszes-vers.html#az-en-ki-emberkent-vazlata-valt':'(Én, ki emberként … )(Vázlat)',
  'versek/osszes-vers.html#enek-magamhoz':'Ének magamhoz',
  'versek/osszes-vers.html#enek-hajolj-ki-ajkamon':'(Ének, hajolj ki ajkamon … )',
  'versek/osszes-vers.html#engem-temetnek':'Engem temetnek',
  'versek/osszes-vers.html#epigramma':'Epigramma',
  'versek/osszes-vers.html#erik-a-feny':'Érik a fény',
  'versek/osszes-vers.html#eroenek':'Erőének',
  'versek/osszes-vers.html#eros-kemeny':'(Erős, kemény … )',
  'versek/osszes-vers.html#erosodik':'Erősödik',
  'versek/osszes-vers.html#erted-haragszom-nem-ellened':'Érted haragszom, nem ellened',
  'versek/osszes-vers.html#erzitek-e':'Érzitek-e?',
  'versek/osszes-vers.html#es-amulok':'(És ámulok … )',
  'versek/osszes-vers.html#es-keressuk-az-igazsagot':'És keressük az igazságot',
  'versek/osszes-vers.html#es-most-nem-tudom-mit-tegyek':'(És most nem tudom, mit tegyek … )',
  'versek/osszes-vers.html#es-testem-vegul-megbetegedett':'(és testem végül megbetegedett … )',
  'versek/osszes-vers.html#esik-1-4':'Esik 1–4 (Esik esik … )',
  'versek/osszes-vers.html#esik-eso-magyar-foldre':'Esik eső magyar földre …',
  'versek/osszes-vers.html#esik':'Esik (Állok, lábamnál tócsa nő … )',
  'versek/osszes-vers.html#eso':'Eső',
  'versek/osszes-vers.html#esoben':'(Esőben … )',
  'versek/osszes-vers.html#este-volt-s-a-borunk-osszeert':'Este volt s a bőrünk összeért',
  'versek/osszes-vers.html#esti-felhokon':'Esti felhőkön',
  'versek/osszes-vers.html#eszmelet':'Eszmélet',
  'versek/osszes-vers.html#eva-vigyazz':'(Éva vigyázz … )',
  'versek/osszes-vers.html#ezen-ujabb-kis-magyarnak':'(Ezen újabb kis magyarnak … )',
  'versek/osszes-vers.html#ezerfarosznyi-vegzet':'Ezerfárosznyi végzet',
  'versek/osszes-vers.html#ezust-elet-1-2':'Ezüst élet 1–2',
  'versek/osszes-vers.html#fagy':'Fagy',
  'versek/osszes-vers.html#fagy-valt':'Fagy (Változat)',
  'versek/osszes-vers.html#fagyon-veszek-vagy-ehen':'(Fagyon veszek, vagy éhen … )',
  'versek/osszes-vers.html#fak':'Fák',
  'versek/osszes-vers.html#falak':'Falak',
  'versek/osszes-vers.html#falu':'Falu',
  'versek/osszes-vers.html#farago-sarinak':'[Faragó Sárinak]',
  'versek/osszes-vers.html#farsangi-lakodalom':'Farsangi lakodalom',
  'versek/osszes-vers.html#favago':'Favágó',
  'versek/osszes-vers.html#favago-valt':'Favágó (Változat)',
  'versek/osszes-vers.html#feherruhaban-atszalad':'(Fehérruhában átszalad … )',
  'versek/osszes-vers.html#felesegem':'Feleségem',
  'versek/osszes-vers.html#felido-0-0':'Félidő: 0–0',
  'versek/osszes-vers.html#ferfiszoval-1-2':'Férfiszóval 1–2',
  'versek/osszes-vers.html#fiatal-asszonyok-eneke':'Fiatal asszonyok éneke',
  'versek/osszes-vers.html#fiatal-eletek-induloja':'Fiatal életek indulója',
  'versek/osszes-vers.html#figyel-a-kancsal':'Figyel a kancsal',
  'versek/osszes-vers.html#flora-1-2':'Flóra 1–2',
  'versek/osszes-vers.html#flora':'Flóra 1–5',
  'versek/osszes-vers.html#flora-csinaljunk-gyereket':'(Flóra, csináljunk gyereket … )',
  'versek/osszes-vers.html#floranak':'Flórának',
  'versek/osszes-vers.html#fohaszkodo-enek':'Fohászkodó ének',
  'versek/osszes-vers.html#fordulo':'Forduló',
  'versek/osszes-vers.html#foldmadar':'Földmadár',
  'versek/osszes-vers.html#forgeteg':'Förgeteg',
  'versek/osszes-vers.html#fozz-neki-luszi-huslevest':'(főzz neki lüszi huslevest … )',
  'versek/osszes-vers.html#furcsa-fohasz-a-sinek-kozott':'Furcsa fohász a sinek között',
  'versek/osszes-vers.html#fust':'Füst',
  'versek/osszes-vers.html#galantai-batyamnak':'Galantai bátyámnak',
  'versek/osszes-vers.html#glas-valt':'Glas',
  'versek/osszes-vers.html#gugyu-gugyu':'Gügyü, gügyü …',
  'versek/osszes-vers.html#gyasz-es-patyolat':'Gyász és patyolat',
  'versek/osszes-vers.html#gyemant':'Gyémánt',
  'versek/osszes-vers.html#gyenge-muharos-mezot':'(Gyenge muharos mezőt … )',
  'versek/osszes-vers.html#gyereksiras':'Gyereksírás',
  'versek/osszes-vers.html#gyermekke-tettel':'Gyermekké tettél',
  'versek/osszes-vers.html#gyongy':'Gyöngy',
  'versek/osszes-vers.html#gyongysor':'Gyöngysor',
  'versek/osszes-vers.html#gyonyorut-lattam':'Gyönyörűt láttam',
  'versek/osszes-vers.html#ha-a-hold-sut':'Ha a hold süt …',
  'versek/osszes-vers.html#ha-elhagysz':'(Ha elhagysz … )',
  'versek/osszes-vers.html#ha-lelked-logikad':'(Ha lelked, logikád … )',
  'versek/osszes-vers.html#ha-lenyed-eros-derito-levegojet':'(Ha lényed erős, deritő levegőjét … )',
  'versek/osszes-vers.html#ha-nem-leszel':'Ha nem leszel …',
  'versek/osszes-vers.html#ha-nem-szoritsz':'(Ha nem szoritsz … )',
  'versek/osszes-vers.html#ha-nem-veszik-eszben':'(Ha nem veszik észben … )',
  'versek/osszes-vers.html#ha-sziu-volnek':'(Ha sziú volnék … )',
  'versek/osszes-vers.html#hajad-az-ujjame':'Hajad az ujjamé …',
  'versek/osszes-vers.html#hajnalban-kel-fol-mint-a-pekek':'Hajnalban kel föl, mint a pékek',
  'versek/osszes-vers.html#hajnali-tiz-ora':'(Hajnali tíz óra … )',
  'versek/osszes-vers.html#hajnali-vers-kedvesemnek':'Hajnali vers kedvesemnek',
  'versek/osszes-vers.html#hajnalvaras':'Hajnalvárás',
  'versek/osszes-vers.html#hajon-megyek-pestre':'Hajón megyek Pestre',
  'versek/osszes-vers.html#hallom-hogy-az-adam':'(Hallom, hogy az Ádám … )',
  'versek/osszes-vers.html#halo':'Háló',
  'versek/osszes-vers.html#hangya':'Hangya',
  'versek/osszes-vers.html#harag':'Harag',
  'versek/osszes-vers.html#harc-a-bekessegert':'Harc a békességért',
  'versek/osszes-vers.html#harmatocska':'Harmatocska',
  'versek/osszes-vers.html#harom-vak-hollo':'(Három vak holló … )',
  'versek/osszes-vers.html#harom-vandor':'[Három vándor]',
  'versek/osszes-vers.html#haszon':'Haszon',
  'versek/osszes-vers.html#hatar':'Határ',
  'versek/osszes-vers.html#hazam-1-7':'Hazám 1–7',
  'versek/osszes-vers.html#herz-henrik-omeltosaganak':'Herz Henrik Őméltóságának',
  'versek/osszes-vers.html#het-napja':'Hét napja',
  'versek/osszes-vers.html#hetert-magamat-kerdem':'(Hétért – magamat kérdem … )',
  'versek/osszes-vers.html#flora':'Hexaméterek',
  'versek/osszes-vers.html#hid-alatt':'Híd alatt',
  'versek/osszes-vers.html#hivogato':'Hivogató',
  'versek/osszes-vers.html#hizlalt-eso-kapirgal':'(Hizlalt eső kapirgál … )',
  'versek/osszes-vers.html#hol-a-miniszterelnok':'(Hol a miniszterelnök … )',
  'versek/osszes-vers.html#holt-videk':'Holt vidék',
  'versek/osszes-vers.html#holttest-az-uccan':'Holttest az uccán',
  'versek/osszes-vers.html#homaly-borult-az-erdore':'Homály borult az erdőre …',
  'versek/osszes-vers.html#homonnai-ibinek':'Homonnai Ibinek',
  'versek/osszes-vers.html#hont-erzsinek':'[Hont Erzsinek]',
  'versek/osszes-vers.html#hosszu-az-uristen':'Hosszú az Úristen',
  'versek/osszes-vers.html#hova-forduljon-az-ember':'(Hová forduljon az ember … )',
  'versek/osszes-vers.html#hozza':'Hozzá!',
  'versek/osszes-vers.html#hull-a-level':'(Hull a levél … )',
  'versek/osszes-vers.html#eve-25':'(25 éve … )',
  'versek/osszes-vers.html#huseg':'Hűség',
  'versek/osszes-vers.html#hymnus-a-borhoz':'Hymnus a borhoz',
  'versek/osszes-vers.html#hymnus-az-elethez':'Hymnus az Élethez',
  'versek/osszes-vers.html#ide-ujra-a-szeretet-jon':'Ide újra a szeretet jön',
  'versek/osszes-vers.html#ifjumunkas':'Ifjúmunkás',
  'versek/osszes-vers.html#igaz-ember':'Igaz ember',
  'versek/osszes-vers.html#igaz-oszinte-bucsu':'Igaz, őszinte búcsú',
  'versek/osszes-vers.html#ige':'[IGE]',
  'versek/osszes-vers.html#illyes-gyulanak':'Illyés Gyulának',
  'versek/osszes-vers.html#imadsag-megfaradtaknak':'Imádság megfáradtaknak',
  'versek/osszes-vers.html#ime-hat-megleltem-hazamat':'(Ime, hát megleltem hazámat … )',
  'versek/osszes-vers.html#indiaban-hol-ejjel-a-vadak':'(Indiában, hol éjjel a vadak … )',
  'versek/osszes-vers.html#invokacio':'Invokáció',
  'versek/osszes-vers.html#irasjel':'Írásjel',
  'versek/osszes-vers.html#irgalom':'Irgalom',
  'versek/osszes-vers.html#irgalom-edesanyam':'(Irgalom, édesanyám … )',
  'versek/osszes-vers.html#isten-en-az-istenem':'Isten (Én az Istenem … )',
  'versek/osszes-vers.html#isten-hogyha-golyoznak':'Isten (Hogyha golyóznak … )',
  'versek/osszes-vers.html#isten-lattam-uram':'Isten (Láttam Uram)',
  'versek/osszes-vers.html#isten-1-4':'Isten 1–4',
  'versek/osszes-vers.html#istenem':'Istenem',
  'versek/osszes-vers.html#istenjaras':'Istenjárás',
  'versek/osszes-vers.html#iszonyat':'Iszonyat',
  'versek/osszes-vers.html#itt-egy-fa-ott-egy-fa':'Itt egy fa, ott egy fa',
  'versek/osszes-vers.html#jaj-azoknak':'(Jaj azoknak … )',
  'versek/osszes-vers.html#jaj-majdnem':'Jaj, majdnem …',
  'versek/osszes-vers.html#je-dois':'(Je dois … )',
  'versek/osszes-vers.html#jelen-mult-jovo':'Jelen, Mult, Jövő',
  'versek/osszes-vers.html#jo-ara-van':'(Jó ára van … )',
  'versek/osszes-vers.html#jo-volna-e':'(Jó volna-e … )',
  'versek/osszes-vers.html#jonal-jobb':'Jónál jobb',
  'versek/osszes-vers.html#jozsef-attila-jozsef-attila-hidd-el':'József Attila (József Attila, hidd el … )',
  'versek/osszes-vers.html#jozsef-attila':'József Attila (Vidám és jó volt … )',
  'versek/osszes-vers.html#jojj-testverkem-valt':'Jöjj testvérkém',
  'versek/osszes-vers.html#jon-a-vihar':'(Jön a vihar … )',
  'versek/osszes-vers.html#jott-megfogott-es-athajitott':'Jött, megfogott és áthajított',
  'versek/osszes-vers.html#jovendo-ferfiak':'Jövendő férfiak',
  'versek/osszes-vers.html#judit':'Judit',
  'versek/osszes-vers.html#judit-versek-toredekei':'[Judit-versek töredékei]',
  'versek/osszes-vers.html#juhasz-gyulahoz':'Juhász Gyulához',
  'versek/osszes-vers.html#juhasz-gyularol-valo-nota':'Juhász Gyuláról való nóta',
  'versek/osszes-vers.html#jut-az-ember':'Jut az ember',
  'versek/osszes-vers.html#jut-most-eleg-virag':'Jut most elég virág',
  'versek/osszes-vers.html#jutka-verse':'Jutka verse',
  'versek/osszes-vers.html#jutkam-csapodj':'(Jutkám, csapódj … )',
  'versek/osszes-vers.html#ket-vers':'K. S. † tbc-ben',
  'versek/osszes-vers.html#kakuk-marci':'Kakuk Marci',
  'versek/osszes-vers.html#kalozkapitany-induloja':'Kalózkapitány indulója',
  'versek/osszes-vers.html#karacsony':'Karácsony',
  'versek/osszes-vers.html#karoval-jottel':'(Karóval jöttél … )',
  'versek/osszes-vers.html#kasasodik-a-viz':'(Kásásodik a víz … )',
  'versek/osszes-vers.html#kedves-joco':'Kedves Jocó!',
  'versek/osszes-vers.html#kedves-zoltan':'(Kedves Zoltán … )',
  'versek/osszes-vers.html#kedvesem-betegen':'(Kedvesem betegen … )',
  'versek/osszes-vers.html#kedvesem':'Kedvesem,',
  'versek/osszes-vers.html#kedveskem':'(Kedveském … )',
  'versek/osszes-vers.html#keltezetlen-toredekek':'[Keltezetlen töredékek]',
  'versek/osszes-vers.html#kep-a-tukorben':'Kép a tükörben',
  'versek/osszes-vers.html#kerek-asztal':'Kerek asztal',
  'versek/osszes-vers.html#keresek-valakit':'Keresek valakit',
  'versek/osszes-vers.html#tunodo':'Keresztény',
  'versek/osszes-vers.html#kertemben-erik-a':'(Kertemben érek a … )',
  'versek/osszes-vers.html#kertesz-leszek':'Kertész leszek',
  'versek/osszes-vers.html#kesei-sirato':'Kései sirató',
  'versek/osszes-vers.html#a-kesei-sirato-vazlataibol-valt':'Kései sirató (Vázlatok)',
  'versek/osszes-vers.html#keseru-nekifohaszkodas':'Keserű nekifohászkodás',
  'versek/osszes-vers.html#keseru':'Keserű',
  'versek/osszes-vers.html#kesz-a-leltar':'Kész a leltár',
  'versek/osszes-vers.html#ket-dal':'Két dal',
  'versek/osszes-vers.html#ket-hexameter':'Két hexameter',
  'versek/osszes-vers.html#ket-keserves':'Két keserves',
  'versek/osszes-vers.html#ket-vazlat':'Két vázlat',
  'versek/osszes-vers.html#ket-vers':'Két vers',
  'versek/osszes-vers.html#ket-vers-kertrol':'Két vers, kertről',
  'versek/osszes-vers.html#ki-lapengedelyt-nekem-nem-adott':'(Ki lapengedélyt nekem nem adott … )',
  'versek/osszes-vers.html#ki-tudom-meg-sokaig-elek':'(Ki tudom, még sokáig élek … )',
  'versek/osszes-vers.html#ki-verne-fol-lelkunkben-a-lelket':'Ki verné föl lelkünkben a lelket?',
  'versek/osszes-vers.html#kialtozas':'Kiáltozás',
  'versek/osszes-vers.html#kialtunk-istenhez':'Kiáltunk Istenhez',
  'versek/osszes-vers.html#ki-be-ugral':'Ki-be ugrál …',
  'versek/osszes-vers.html#kik-csak-hallottak-a-szerelem-hirit':'(Kik csak hallották a szerelem hírit … )',
  'versek/osszes-vers.html#kiknek-adtam-a-boldogot-valt':'(Kiknek adtam a boldogot … )',
  'versek/osszes-vers.html#kilometerekkel':'Kilóméterekkel',
  'versek/osszes-vers.html#kinalgato':'[Kínálgató]',
  'versek/osszes-vers.html#kinos-szogletes-mulasom-valt':'Kínos, szögletes mulásom',
  'versek/osszes-vers.html#kirakjak-a-fat':'Kirakják a fát',
  'versek/osszes-vers.html#kirakom-roggel-valt':'Kirakom röggel',
  'versek/osszes-vers.html#toredekek-1923':'(Kis Asszonyom ne sírj … )',
  'versek/osszes-vers.html#kispolgar':'Kispolgár',
  'versek/osszes-vers.html#kiszombori-dal':'Kiszombori dal',
  'versek/osszes-vers.html#klarisok':'Klárisok',
  'versek/osszes-vers.html#koldus':'Koldus',
  'versek/osszes-vers.html#koldusok-1-3':'Koldusok 1–3',
  'versek/osszes-vers.html#komoly-lett-mar':'Komoly lett már',
  'versek/osszes-vers.html#kopogtatas-nelkul':'Kopogtatás nélkül',
  'versek/osszes-vers.html#kosztolanyi':'Kosztolányi',
  'versek/osszes-vers.html#kovacs':'Kovács',
  'versek/osszes-vers.html#kodbol-csondbol':'Ködből, csöndből',
  'versek/osszes-vers.html#kolto-szerelme-szalmalang':'(Költő szerelme szalmaláng … )',
  'versek/osszes-vers.html#koltonk-es-kora':'„Költőnk és Kora”',
  'versek/osszes-vers.html#koltoszerelem-teremto-estje':'Költőszerelem teremtő estje',
  'versek/osszes-vers.html#kontosok':'Köntösök',
  'versek/osszes-vers.html#konnyu-emlekek':'(Könnyű emlékek … )',
  'versek/osszes-vers.html#konnyu-feher-ruhaban':'Könnyű, fehér ruhában',
  'versek/osszes-vers.html#kovek':'Kövek',
  'versek/osszes-vers.html#kukoricafold':'Kukoricaföld',
  'versek/osszes-vers.html#kultura':'Kultúra',
  'versek/osszes-vers.html#kulvarosi-ej':'Külvárosi éj',
  'versek/osszes-vers.html#laci-ba':'Laci bá’',
  'versek/osszes-vers.html#lagy-tajek-valt':'(Lágy tájék … )',
  'versek/osszes-vers.html#nagy-lajosnak':'(Lajos, ha … )',
  'versek/osszes-vers.html#lanyszepseg-dicserete-1-2':'Lányszépség dícsérete 1–2',
  'versek/osszes-vers.html#lanyszepseg-dicserete':'Lányszépség dícsérete (Dícsérlek hát … )',
  'versek/osszes-vers.html#remenytelenul':'Lassan, tünődve',
  'versek/osszes-vers.html#lassu-almodozasaibol':'(Lassú álmodozásaiból … )',
  'versek/osszes-vers.html#latod':'Látod?',
  'versek/osszes-vers.html#lazado-krisztus':'Lázadó Krisztus',
  'versek/osszes-vers.html#lazado-szentek':'Lázadó szentek',
  'versek/osszes-vers.html#le-vagyok-gyozve':'(Le vagyok győzve … )',
  'versek/osszes-vers.html#leanykero-enek':'Leánykérő ének',
  'versek/osszes-vers.html#lebukott':'Lebukott',
  'versek/osszes-vers.html#legalabb-20-fok-hideg-van':'(Legalább 20 fok hideg van … )',
  'versek/osszes-vers.html#legy-ostoba':'Légy ostoba',
  'versek/osszes-vers.html#lelekszirteken':'Lélekszirteken',
  'versek/osszes-vers.html#leontin':'[Leontin]',
  'versek/osszes-vers.html#lepte-konnyu':'(Lépte könnyü … )',
  'versek/osszes-vers.html#toredekek-1935':'(lesz lágy hús … )',
  'versek/osszes-vers.html#leulepszik':'(Leülepszik … )',
  'versek/osszes-vers.html#levegot':'Levegőt!',
  'versek/osszes-vers.html#level':'[Levél]',
  'versek/osszes-vers.html#lopok-kozott-szegenyember':'Lopók között szegényember',
  'versek/osszes-vers.html#lovas-a-temetoben':'Lovas a temetőben',
  'versek/osszes-vers.html#luca':'Luca',
  'versek/osszes-vers.html#lucahoz':'Lucához',
  'versek/osszes-vers.html#ma-lucie':'(Ma Lucie … )',
  'versek/osszes-vers.html#ma-nevnapja-van':'(Ma névnapja van … )',
  'versek/osszes-vers.html#magad-emeszto':'(Magad emésztő … )',
  'versek/osszes-vers.html#magany':'Magány',
  'versek/osszes-vers.html#magyar-alfold':'Magyar Alföld',
  'versek/osszes-vers.html#magyarok-1-2':'Magyarok 1–2',
  'versek/osszes-vers.html#magyarok':'Magyarok',
  'versek/osszes-vers.html#magyarorszag-messzire-van':'(Magyarország messzire van … )',
  'versek/osszes-vers.html#majd-csondbe-fagynak-a-dalok':'(Majd csöndbe fagynak a dalok … )',
  'versek/osszes-vers.html#majd-emlekezni-jo-lesz':'Majd emlékezni jó lesz',
  'versek/osszes-vers.html#majd-megoregszel':'Majd megöregszel',
  'versek/osszes-vers.html#majd':'Majd …',
  'versek/osszes-vers.html#majus':'Május',
  'versek/osszes-vers.html#majusi-enek':'Májusi ének',
  'versek/osszes-vers.html#mama':'Mama',
  'versek/osszes-vers.html#mamor':'Mámor',
  'versek/osszes-vers.html#mancinak-es-miskanak':'Mancinak (és Miskának)',
  'versek/osszes-vers.html#mar-arra-gondolok-nem-egyszer':'(Már arra gondolok nem egyszer … )',
  'versek/osszes-vers.html#mar-ket-milliard':'Már két milliárd',
  'versek/osszes-vers.html#mar-regesreg':'(Már régesrég … )',
  'versek/osszes-vers.html#marcius-1-2':'Március 1–2 (Langy, permeteg eső … )',
  'versek/osszes-vers.html#marcius':'Március (A föld alól … )',
  'versek/osszes-vers.html#margareta':'Margaréta',
  'versek/osszes-vers.html#medalia':'Medália',
  'versek/osszes-vers.html#medaliak':'Medáliák',
  'versek/osszes-vers.html#medaliak-valt':'[Medáliák] (Változatok)',
  'versek/osszes-vers.html#medvetanc':'Medvetánc',
  'versek/osszes-vers.html#meg-ne-utazz-el-sarikam':'(Még ne utazz el, Sárikám … )',
  'versek/osszes-vers.html#meg-nem-volt-olyan-diszno':'(Még nem volt olyan disznó … )',
  'versek/osszes-vers.html#megfaradt-ember':'Megfáradt ember',
  'versek/osszes-vers.html#meghalt-juhasz-gyula':'Meghalt Juhász Gyula',
  'versek/osszes-vers.html#megis-elveszem':'Mégis elveszem',
  'versek/osszes-vers.html#megmeressel':'Megméressél!',
  'versek/osszes-vers.html#meggy-a-koron-valt':'Meggy a kórón',
  'versek/osszes-vers.html#mert-hagytal-el-hogyha-kivansz':'Mért hagytál el, hogyha kívánsz',
  'versek/osszes-vers.html#mi-emberek':'(Mi emberek … )',
  'versek/osszes-vers.html#miben-hisztek':'Miben hisztek …',
  'versek/osszes-vers.html#miert-mondottal-rosszat-nekem':'Miért mondottál rosszat nékem',
  'versek/osszes-vers.html#mikent-a-tiszta-urben':'(Miként a tiszta űrben … )',
  'versek/osszes-vers.html#mikor-a-szeretok-valt':'Mikor a szeretők',
  'versek/osszes-vers.html#mikor-az-uccan-atment-a-kedves':'Mikor az uccán átment a kedves',
  'versek/osszes-vers.html#mikor-az-uccan-atment-a-kedves-valt':'Mikor az uccán átment a kedves (Változat)',
  'versek/osszes-vers.html#mikor-dolgozol-csendesen':'(Mikor dolgozol csendesen … )',
  'versek/osszes-vers.html#mily-szep-vagy':'(Mily szép vagy … )',
  'versek/osszes-vers.html#milyen-jo-lenne-nem-utni-vissza':'Milyen jó lenne nem ütni vissza',
  'versek/osszes-vers.html#minden-rendu-emberi-dolgokhoz':'Minden rendű emberi dolgokhoz',
  'versek/osszes-vers.html#minden-s-mindenki-szeret-engem':'(Minden s mindenki szeret engem … )',
  'versek/osszes-vers.html#mindent-hagyok':'Mindent hagyok',
  'versek/osszes-vers.html#mindig-jotanacsot-sziszegnek':'(Mindig jótanácsot sziszegnek … )',
  'versek/osszes-vers.html#mint-a-mezon':'Mint a mezőn …',
  'versek/osszes-vers.html#mint-a-motor-mely-mar-begyulladt':'(Mint a motor, mely már begyulladt … )',
  'versek/osszes-vers.html#mint-a-tejut-a-vonulo':'(Mint a Tejút a vonuló … )',
  'versek/osszes-vers.html#mint-gyermek':'Mint gyermek …',
  'versek/osszes-vers.html#mint-locspocs-fenyeben':'(mint locspocs-fényben … )',
  'versek/osszes-vers.html#mint-loholo-bolond-elott':'(Mint loholó bolond előtt … )',
  'versek/osszes-vers.html#mint-oroszlan':'(mint oroszlán … )',
  'versek/osszes-vers.html#mint-orok-keservet':'(Mint örök keservet … )',
  'versek/osszes-vers.html#mint-tenger-alol':'(Mint tenger alól … )',
  'versek/osszes-vers.html#miota-egyeb-nagy-irok':'(Mióta egyéb nagy írók … )',
  'versek/osszes-vers.html#miota-elmentel':'Mióta elmentél',
  'versek/osszes-vers.html#mivelhogy-oly-szepen-terit-a':'(Mivelhogy oly szépen terít a … )',
  'versek/osszes-vers.html#modern-szonett':'Modern szonett',
  'versek/osszes-vers.html#mondd-mit-erlel':'Mondd, mit érlel …',
  'versek/osszes-vers.html#most-a-teremtes-kezdeten-vagyunk':'Most a teremtés kezdetén vagyunk',
  'versek/osszes-vers.html#most-feher-a-tuz':'Most fehér a tűz',
  'versek/osszes-vers.html#munkas':'Munkás',
  'versek/osszes-vers.html#munkashalal':'Munkáshalál',
  'versek/osszes-vers.html#munkasok-korusa':'Munkások Kórusa',
  'versek/osszes-vers.html#munkasok':'Munkások',
  'versek/osszes-vers.html#muterem':'Műterem',
  'versek/osszes-vers.html#muveszet-az-emberek-kozott':'Művészet az emberek között',
  'versek/osszes-vers.html#nagy-ajandekok-tora':'Nagy ajándékok tora',
  'versek/osszes-vers.html#nagy-lajosnak':'[Nagy Lajosnak]',
  'versek/osszes-vers.html#nagy-varosokrol-beszelt-a-messzi-vandor':'Nagy városokról beszélt a messzi vándor',
  'versek/osszes-vers.html#nagyon-faj':'Nagyon fáj',
  'versek/osszes-vers.html#nappal-mint-foldet-vad-homok':'(Nappal mint földet vad homok … )',
  'versek/osszes-vers.html#napszonett':'Napszonett',
  'versek/osszes-vers.html#ne-bantsd':'Ne bántsd',
  'versek/osszes-vers.html#ne-legy-szeles':'(Ne légy szeles … )',
  'versek/osszes-vers.html#negyen-ugrottunk-vizbe':'Négyen ugrottunk vízbe',
  'versek/osszes-vers.html#neha-szigetek':'Néha szigetek',
  'versek/osszes-vers.html#nehany-ejjelre-padra-kore-valt':'Néhány éjjelre padra, kőre',
  'versek/osszes-vers.html#nekem-mindegy':'Nekem mindegy …',
  'versek/osszes-vers.html#nem-emel-fol':'Nem emel föl',
  'versek/osszes-vers.html#nem-en-kialtok':'Nem én kiáltok',
  'versek/osszes-vers.html#nem-er-szerencse':'(Nem ér szerencse … )',
  'versek/osszes-vers.html#nem-talalok-szavakat':'(Nem találok szavakat … )',
  'versek/osszes-vers.html#nem-tudunk-elni':'Nem tudunk élni',
  'versek/osszes-vers.html#nem-nem-kellene-kialtoznom':'(Nem! nem! kellene kiáltoznom … )',
  'versek/osszes-vers.html#nem-nem-soha':'Nem! Nem! Soha!',
  'versek/osszes-vers.html#nemeth-andor':'Németh Andor',
  'versek/osszes-vers.html#nemeth-andor-valt':'németh andor (Változat)',
  'versek/osszes-vers.html#nemzett-jozsef-aron':'Nemzett József Áron',
  'versek/osszes-vers.html#ringelnatz-morgenstern-nepdal':'Népdalok à la Ringelnatz Morgenstern',
  'versek/osszes-vers.html#nevnapi-dicseret':'Névnapi dícséret',
  'versek/osszes-vers.html#nezem-a-lampat':'Nézem a lámpát',
  'versek/osszes-vers.html#nincs-kozom-senkihez':'(Nincs közöm senkihez … )',
  'versek/osszes-vers.html#nor-coc':'[Nor-coc]',
  'versek/osszes-vers.html#no-a-tukor-elott':'Nő a tükör előtt',
  'versek/osszes-vers.html#nyar':'Nyár',
  'versek/osszes-vers.html#nyar-valt':'Nyár (Változat)',
  'versek/osszes-vers.html#nyar-volt':'Nyár volt',
  'versek/osszes-vers.html#nyari-delutan-a-szobaban':'Nyári délután a szobában',
  'versek/osszes-vers.html#nyari-delutan':'Nyári délután',
  'versek/osszes-vers.html#nyari-konnyu-szellok':'(Nyári, könnyű szellők … )',
  'versek/osszes-vers.html#nyolcesztendos-lanyok':'Nyolcesztendős lányok',
  'versek/osszes-vers.html#nyuzsog-a-boldogsag':'(Nyüzsög a boldogság … )',
  'versek/osszes-vers.html#o-banat':'(Ó bánat … )',
  'versek/osszes-vers.html#o-europa-hany-redo':'(Ó Európa hány redő … )',
  'versek/osszes-vers.html#o-szoke-csokok-partja':'(Ó szőke csókok partja … )',
  'versek/osszes-vers.html#o-zordon-szepseg':'Ó zordon Szépség …',
  'versek/osszes-vers.html#oda':'Óda',
  'versek/osszes-vers.html#odvas-fogban':'(Odvas fogban … )',
  'versek/osszes-vers.html#oh-hittem-volna-inkabb':'(Óh hittem volna inkább … )',
  'versek/osszes-vers.html#oh-sziv-nyugodj':'Óh szív! nyugodj!',
  'versek/osszes-vers.html#oly-friss':'Oly friss',
  'versek/osszes-vers.html#oly-lagy-az-este':'(Oly lágy az este … )',
  'versek/osszes-vers.html#olyan-bolond-vagy':'Olyan bolond vagy',
  'versek/osszes-vers.html#ombarge-palot-sous-la-peau-valt':'ombrage pâlot sous la peau',
  'versek/osszes-vers.html#ordas':'Ordas',
  'versek/osszes-vers.html#osztas-utan':'Osztás után',
  'versek/osszes-vers.html#onarckep':'Önarckép',
  'versek/osszes-vers.html#ordog-faraba':'(Ördög farába … )',
  'versek/osszes-vers.html#oreg-minden':'Öreg minden',
  'versek/osszes-vers.html#oregem-no':'(Öregem, no … )',
  'versek/osszes-vers.html#orokkon-haborog-a-tenger':'(Örökkön háborog a tenger … )',
  'versek/osszes-vers.html#os-patkany-terjeszt-kort':'(Ős patkány terjeszt kórt … )',
  'versek/osszes-vers.html#osapam':'Ősapám',
  'versek/osszes-vers.html#osz-valt':'Ősz (A fán a levelek … )',
  'versek/osszes-vers.html#osz':'Ősz (Tar ágak-bogak rácsai között … )',
  'versek/osszes-vers.html#oszi-alkonyat':'Őszi alkonyat',
  'versek/osszes-vers.html#osszetort-szivem':'Összetört szívem …',
  'versek/osszes-vers.html#ot-szegeny-szol':'Öt szegény szól',
  'versek/osszes-vers.html#pancelvonat':'Páncélvonat',
  'versek/osszes-vers.html#pap-a-templomban':'Pap a templomban',
  'versek/osszes-vers.html#parasztanyoka':'Parasztanyóka',
  'versek/osszes-vers.html#parbeszed':'Párbeszéd',
  'versek/osszes-vers.html#parizsi-anzix':'Párizsi anzix',
  'versek/osszes-vers.html#pauvre-plaint-chant-mechant':'Pauvre plaint-chant méchant',
  'versek/osszes-vers.html#perc':'Perc',
  'versek/osszes-vers.html#pernyetancra':'Pernyetáncra',
  'versek/osszes-vers.html#petite-jeanette':'(Petite Jeanette … )',
  'versek/osszes-vers.html#petofi-tuze':'Petőfi tüze',
  'versek/osszes-vers.html#pilota':'Pilóta',
  'versek/osszes-vers.html#piros-hold-korul':'Piros hold körül',
  'versek/osszes-vers.html#pirosszemu':'Pirosszemű',
  'versek/osszes-vers.html#poganyos-hitvallas-magyarul':'Pogányos hitvallás magyarul',
  'versek/osszes-vers.html#pohar':'Pohár',
  'versek/osszes-vers.html#pottyos':'Pöttyös',
  'versek/osszes-vers.html#predikacio':'Prédikáció',
  'versek/osszes-vers.html#proletardal-valt':'Proletárdal',
  'versek/osszes-vers.html#proletarok':'Proletárok!',
  'versek/osszes-vers.html#pucer-csapat-dobog':'(Pucér csapat dobog … )',
  'versek/osszes-vers.html#punkosd-elott':'Pünkösd előtt',
  'versek/osszes-vers.html#ragyog-az-eg':'(Ragyog az ég … )',
  'versek/osszes-vers.html#reggeli-feny':'Reggeli fény',
  'versek/osszes-vers.html#reggeli':'Reggeli',
  'versek/osszes-vers.html#regos-enek':'Regös ének',
  'versek/osszes-vers.html#rejtelmek':'Rejtelmek',
  'versek/osszes-vers.html#remenytelenul':'Reménytelenül',
  'versek/osszes-vers.html#repedt-kalyhamon-macska-ul':'(Repedt kályhámon macska ül … )',
  'versek/osszes-vers.html#reszeg-a-sineken':'Részeg a síneken',
  'versek/osszes-vers.html#rianak-hivom':'Riának hívom',
  'versek/osszes-vers.html#ringato':'Ringató',
  'versek/osszes-vers.html#ringelnatz-morgenstern-szellem':'Ringelnatz Morgenstern, avagy a szellem diadala napjainkban',
  'versek/osszes-vers.html#ritkas-erdo-alatt':'Ritkás erdő alatt',
  'versek/osszes-vers.html#rokkantak':'Rokkantak',
  'versek/osszes-vers.html#roskad-a-kormos-ho':'(Roskad a kormos hó … )',
  'versek/osszes-vers.html#rossz-volt-elszeledt-szivembol':'Rossz volt, elszéledt szivemből',
  'versek/osszes-vers.html#rog-a-roghoz':'Rög a röghöz',
  'versek/osszes-vers.html#rovid-oda-a-kelo-naphoz':'Rövid óda a kelő Naphoz',
  'versek/osszes-vers.html#s-az-en-apam-az-en-anyam':'(S az én apám, az én anyám … )',
  'versek/osszes-vers.html#s-ha-nem-volt-meg-halalos-szerelem':'(s ha nem volt még halálos szerelem … )',
  'versek/osszes-vers.html#s-o-te-szerencsetlen':'(S ó te szerencsétlen … )',
  'versek/osszes-vers.html#sacrilegium':'Sacrilegium',
  'versek/osszes-vers.html#sarga-fuvek':'Sárga füvek',
  'versek/osszes-vers.html#sas':'Sas',
  'versek/osszes-vers.html#segitsetek-hogy-meg-ne-oljem':'(Segítsetek, hogy meg ne öljem … )',
  'versek/osszes-vers.html#semmi':'Semmi',
  'versek/osszes-vers.html#ket-vazlat':'Simon Jolán',
  'versek/osszes-vers.html#simon-jolan-valt':'simon jolán (Változat)',
  'versek/osszes-vers.html#sirdomb-a-hegycsucson':'Sírdomb a hegycsúcson',
  'versek/osszes-vers.html#sohaj':'Sóhaj',
  'versek/osszes-vers.html#sok-gondom-kozt':'Sok gondom közt',
  'versek/osszes-vers.html#sokan-voltak-es-korulvettek':'(Sokan voltak és körülvettek … )',
  'versek/osszes-vers.html#somogyi-lolinak':'Somogyi Lolinak',
  'versek/osszes-vers.html#spleen':'Spleen',
  'versek/osszes-vers.html#sportirodalom':'Sportirodalom',
  'versek/osszes-vers.html#szabados-dal':'Szabados dal',
  'versek/osszes-vers.html#szaggatlak-mint-a-fergeteg':'(Szaggatlak, mint a fergeteg … )',
  'versek/osszes-vers.html#szallj-koltemeny':'(Szállj költemény … )',
  'versek/osszes-vers.html#szamar-szellel-pajtaskodni-ven':'(Szamár széllel pajtáskodni vén … )',
  'versek/osszes-vers.html#szamvetes':'Számvetés',
  'versek/osszes-vers.html#szappanosviz':'Szappanosvíz',
  'versek/osszes-vers.html#szappanosviz-valt':'Szappanosvíz (Változat)',
  'versek/osszes-vers.html#szaradok-torodom':'Száradok, törődöm',
  'versek/osszes-vers.html#szaz-ejszakan':'(Száz éjszakán … )',
  'versek/osszes-vers.html#szeged-alatt':'Szeged alatt',
  'versek/osszes-vers.html#szegeny-ember-hova-menjen':'(Szegény ember hova menjen … )',
  'versek/osszes-vers.html#szegeny-keszi':'(Szegény Keszi … )',
  'versek/osszes-vers.html#szegenyember-balladaja':'Szegényember balladája',
  'versek/osszes-vers.html#szegenyember-szeretoje':'Szegényember szeretője',
  'versek/osszes-vers.html#szegenyseg-szennylepleiben':'(Szegénység szennylepleiben … )',
  'versek/osszes-vers.html#szel-csapta':'(Szél csapta … )',
  'versek/osszes-vers.html#szelid-bucsuzo-asszony':'Szelid, búcsúzó asszony',
  'versek/osszes-vers.html#szelkialto-madar':'Szélkiáltó madár',
  'versek/osszes-vers.html#szelnevelo-tagas-pusztan':'(Szélnevelő, tágas pusztán … )',
  'versek/osszes-vers.html#szep-csondesen-aludj':'Szép csöndesen aludj',
  'versek/osszes-vers.html#szep-lobogoval-vagy-anelkul':'Szép lobogóval, vagy anélkül',
  'versek/osszes-vers.html#szep-artatlan':'(Szép, ártatlan … )',
  'versek/osszes-vers.html#szep-nyari-este-van':'Szép, nyári este van',
  'versek/osszes-vers.html#szepen-beszelsz':'(Szépen beszélsz!… )',
  'versek/osszes-vers.html#szerelem-ez':'Szerelem ez?',
  'versek/osszes-vers.html#szerelmes-keseru-hazafisag':'Szerelmes keserű hazafiság',
  'versek/osszes-vers.html#szerelmes-kiszolas':'Szerelmes kiszólás',
  'versek/osszes-vers.html#szerelmes-vers':'Szerelmes vers',
  'versek/osszes-vers.html#szeretem-s-ezert-megolom':'(Szeretem s ezért megölöm … )',
  'versek/osszes-vers.html#szeretnem-ha-vadalmafa-lennek':'Szeretném, ha vadalmafa lennék!',
  'versek/osszes-vers.html#szeretnenek':'Szeretnének',
  'versek/osszes-vers.html#szeretok-lazadasa':'Szeretők lázadása',
  'versek/osszes-vers.html#szeretok':'Szeretők',
  'versek/osszes-vers.html#szerettek-ignotus-pali':'(Szerették: Ignotus Pali … )',
  'versek/osszes-vers.html#szocialistak-fajas-nyomor':'Szocialisták (Fájás, nyomor … )',
  'versek/osszes-vers.html#szocialistak':'Szocialisták (Le a kapitalizmussal!… )',
  'versek/osszes-vers.html#szol-a-szaja-szolitatlan':'(Szól a szája szólitatlan … )',
  'versek/osszes-vers.html#szol-a-telefon':'(Szól a telefon … )',
  'versek/osszes-vers.html#szolganak-allitod-magad':'(Szolgálnak állitod magad … )',
  'versek/osszes-vers.html#toredekek-1936':'(Szólj hát, mit tegyek én … )',
  'versek/osszes-vers.html#szoljon-e-koltemeny-arrol':'(Szóljon e költemény arról … )',
  'versek/osszes-vers.html#szolt-az-ember':'Szólt az ember',
  'versek/osszes-vers.html#szomorufuz':'Szomorúfűz',
  'versek/osszes-vers.html#szonettjatek':'[Szonettjáték]',
  'versek/osszes-vers.html#szoke-hajam':'(Szőke hajam … )',
  'versek/osszes-vers.html#szuletesnapomra':'Születésnapomra',
  'versek/osszes-vers.html#szurkulet':'[Szürkület]',
  'versek/osszes-vers.html#tajvers-toredekek':'[Tájvers-töredékek]',
  'versek/osszes-vers.html#talan-eltunok-hirtelen':'(Talán eltünök hirtelen … )',
  'versek/osszes-vers.html#tancba-fognak':'Táncba fognak',
  'versek/osszes-vers.html#tanitasok':'Tanítások',
  'versek/osszes-vers.html#tanulmanyfej':'Tanulmányfej',
  'versek/osszes-vers.html#tavasz-van-gyonyoru':'Tavasz van! Gyönyörű!',
  'versek/osszes-vers.html#tavaszi-enek':'Tavaszi ének',
  'versek/osszes-vers.html#tavaszi-labdajatek':'Tavaszi labdajáték',
  'versek/osszes-vers.html#tavaszi-sar':'Tavaszi sár',
  'versek/osszes-vers.html#tavol-tar-agak-szerkezetei':'(távol tar ágak szerkezetei … )',
  'versek/osszes-vers.html#tavol-zongora-mellett':'Távol zongora mellett',
  'versek/osszes-vers.html#tavoli-enek':'Távoli ének',
  'versek/osszes-vers.html#te-ongyilkos':'(Te öngyilkos … )',
  'versek/osszes-vers.html#tedd-a-kezed':'Tedd a kezed',
  'versek/osszes-vers.html#teged-siratlak':'(Téged siratlak … )',
  'versek/osszes-vers.html#tehervonatok-tolatnak':'(Tehervonatok tolatnak … )',
  'versek/osszes-vers.html#tel':'Tél',
  'versek/osszes-vers.html#teli-ejszaka':'Téli éjszaka',
  'versek/osszes-vers.html#temetes-utan':'Temetés után',
  'versek/osszes-vers.html#templom-hulla-rozsa':'Templom; hulla; rózsa',
  'versek/osszes-vers.html#tengerhez':'Tengerhez',
  'versek/osszes-vers.html#tenyeremre-tettem':'(Tenyeremre tettem … )',
  'versek/osszes-vers.html#tettamanti-belanak':'[Tettamanti Bélának]',
  'versek/osszes-vers.html#thomas-mann-udvozlese':'Thomas Mann üdvözlése',
  'versek/osszes-vers.html#ti-jok-vagytok-mindannyian':'Ti jók vagytok mindannyian',
  'versek/osszes-vers.html#tiszazug':'Tiszazug',
  'versek/osszes-vers.html#tiszta-szivvel':'Tiszta szívvel',
  'versek/osszes-vers.html#tizenot-eve-irok-koltemenyt':'(Tizenőt éve írok költeményt … )',
  'versek/osszes-vers.html#tollaszkodik-a-sarga-lomb':'(Tollászkodik a sárga lomb … )',
  'versek/osszes-vers.html#toszunnyado':'Tószunnyadó',
  'versek/osszes-vers.html#tovabb-en-nem-birom':'Tovább én nem birom',
  'versek/osszes-vers.html#tomeg':'Tömeg',
  'versek/osszes-vers.html#toredekek-1923':'[Töredékek] (1923)',
  'versek/osszes-vers.html#toredekek-1927':'[Töredékek] (1927)',
  'versek/osszes-vers.html#toredekek-1931':'[Töredékek] (1931)',
  'versek/osszes-vers.html#toredekek-1934':'[Töredékek] (1934)',
  'versek/osszes-vers.html#toredekek-1935':'[Töredékek] (1935)',
  'versek/osszes-vers.html#toredekek-1936':'[Töredékek] (1936)',
  'versek/osszes-vers.html#toredekek-1-1937':'[Töredékek] (1937 tavasza–nyara)',
  'versek/osszes-vers.html#toredekek-2-1937':'[Töredékek] (1937. okt.–nov.)',
  'versek/osszes-vers.html#toredekes-rogtonzesek-tormeleksorok':'[Töredékes rögtönzések, törmeléksorok]',
  'versek/osszes-vers.html#tudod-hogy-nincs-bocsanat':'Tudod, hogy nincs bocsánat',
  'versek/osszes-vers.html#tudtam-en':'Tudtam én',
  'versek/osszes-vers.html#tusikanak':'Tusikának',
  'versek/osszes-vers.html#tunodo':'Tűnődő',
  'versek/osszes-vers.html#tuntetes':'Tüntetés',
  'versek/osszes-vers.html#tuz-van':'Tűz van!',
  'versek/osszes-vers.html#tuzek-eneke':'Tüzek éneke',
  'versek/osszes-vers.html#tuzek-eneke-valt':'Tüzek éneke (Változat)',
  'versek/osszes-vers.html#ugy-elsz-szivemben-erzsi':'(Ugy élsz, szivemben, Erzsi … )',
  'versek/osszes-vers.html#ugy-eltunt':'(ugy eltünt … )',
  'versek/osszes-vers.html#ugy-e-pajtas':'Ugy-e pajtás!',
  'versek/osszes-vers.html#uram':'Uram!',
  'versek/osszes-vers.html#utrahivas':'Útrahívás',
  'versek/osszes-vers.html#utrakeszseg':'Útrakészség',
  'versek/osszes-vers.html#udvozles':'Üdvözlés',
  'versek/osszes-vers.html#ulni-allni-olni-halni':'Ülni, állni, ölni, halni',
  'versek/osszes-vers.html#ulunk-egymas-mellett':'Ülünk egymás mellett',
  'versek/osszes-vers.html#uvegontok':'Üvegöntők',
  'versek/osszes-vers.html#vadasz-szemunkre':'(vadász szemünkre … )',
  'versek/osszes-vers.html#vagymagam-a-hold-alatt':'Vágymagam a Hold alatt',
  'versek/osszes-vers.html#vagyok-kinek-kell-legyen-kedve-valt':'Vagyok, kinek kell, legyen kedve!',
  'versek/osszes-vers.html#vak-vak-vak':'(Vak, vak, vak … )',
  'versek/osszes-vers.html#valamikor-volt-a-tett':'(Valamikor volt a tett … )',
  'versek/osszes-vers.html#varakozas':'Várakozás',
  'versek/osszes-vers.html#varlak':'Várlak',
  'versek/osszes-vers.html#vasarhelyrol-diszno-jo':'(Vásárhelyről disznó jő … )',
  'versek/osszes-vers.html#vas-szinu-egboltban':'Vas-színű égboltban …',
  'versek/osszes-vers.html#vegtelen-ota':'Végtelen óta …',
  'versek/osszes-vers.html#vegul':'Végül',
  'versek/osszes-vers.html#verre-valt':'Verre',
  'versek/osszes-vers.html#versek-vegere':'Versek végére',
  'versek/osszes-vers.html#versem-komor':'(Versem komor … )',
  'versek/osszes-vers.html#vigasz':'Vigasz',
  'versek/osszes-vers.html#vigasztald-meg-valt':'(Vigasztald meg … )',
  'versek/osszes-vers.html#tunodo':'Vihar',
  'versek/osszes-vers.html#vilag-megokolt-utalata':'Világ megokolt útálata',
  'versek/osszes-vers.html#vilagokat-igazgatok':'(világokat igazgatok … )',
  'versek/osszes-vers.html#vilagositsd-fol':'Világosítsd föl',
  'versek/osszes-vers.html#villamok-szeretoje':'Villámok szeretője',
  'versek/osszes-vers.html#virag':'Virág',
  'versek/osszes-vers.html#viragos':'Virágos',
  'versek/osszes-vers.html#viszem-a-foldem':'Viszem a földem',
  'versek/osszes-vers.html#wolke':'Wolke',
  'versek/osszes-vers.html#zoologus-ha':'(Zoológus ha … )',
  'versek/osszes-vers.html#zold-napsutes-hintalt':'(Zöld napsütés hintált … )',
  'versek/osszes-vers.html#zugo-feher':'(Zúgó, fehér … )',
  'versek/osszes-vers.html#zuzmara':'Zuzmara',
  'versek/osszes-vers.html#1916-17':'1916–1917-es versek',
  'versek/osszes-vers.html#1920':'1920-as versek',
  'versek/osszes-vers.html#1921':'1921-es versek',
  'versek/osszes-vers.html#1922':'1922-es versek',
  'versek/osszes-vers.html#1923':'1923-as versek',
  'versek/osszes-vers.html#1924':'1924-es versek',
  'versek/osszes-vers.html#1925':'1925-ös versek',
  'versek/osszes-vers.html#1926':'1926-os versek',
  'versek/osszes-vers.html#1927':'1927-es versek',
  'versek/osszes-vers.html#1928':'1928-as versek',
  'versek/osszes-vers.html#1929':'1929-es versek',
  'versek/osszes-vers.html#1930':'1930-as versek',
  'versek/osszes-vers.html#1931':'1931-es versek',
  'versek/osszes-vers.html#1932':'1932-es versek',
  'versek/osszes-vers.html#1933':'1933-as versek',
  'versek/osszes-vers.html#1934':'1934-es versek',
  'versek/osszes-vers.html#1935':'1935-ös versek',
  'versek/osszes-vers.html#1936':'1936-os versek',
  'versek/osszes-vers.html#1937':'1937-es versek',
  'versek/osszes-vers.html#valtozatok':'Változatok',
  'versek/osszes-vers.html#rogtonzesek':'Rögtönzések',
  'versek/osszes-vers.html#veronika':'Emlékül Veronikának',
  'versek/osszes-vers.html#zsaklin':'Zsaklinnak',
  'irasok/osszes-proza.html':'Szabad-ötletek jegyzéke',
  'irasok/osszes-proza.html#cv':'Curriculum vitae',
  'irasok/osszes-proza.html#piros-tortenet':'Piros történet (széppróza)',
  'irasok/osszes-proza.html#istvan-a-banyasz':'István, a bányász (széppróza)',
  'irasok/osszes-proza.html#tizenot-nap-az-uvegburaban':'Tizenöt nap az üvegbúrában (széppróza)',
  'irasok/osszes-proza.html#csoszogi-az-oreg-suszter':'Csoszogi, az öreg suszter (széppróza)',
  'irasok/osszes-proza.html#dramatoredek':'Drámatöredék',
  'irasok/osszes-proza.html#phe-ji-gjoh-ugyanis':'[Phe-Ji-Gjoh ugyanis … ]',
  'irasok/osszes-proza.html#kirpotin':'[Kirpotin … ]',
  'irasok/osszes-proza.html#nyelvunk-izei':'[Nyelvünk ízei … ]',
  'irasok/osszes-proza.html#somlainenak':'[Somlainénak … ]',
  'irasok/osszes-proza.html#verstan-es-versiras':'Verstan és versirás',
  'irasok/osszes-proza.html#ember-a-salakon':'Ember a salakon',
  'irasok/osszes-proza.html#johiszemu-tevedes':'[Jóhiszemű tévedés … ]',
  'irasok/osszes-proza.html#medvetanc-proza':'Medvetánc',
  'irasok/osszes-proza.html#kautsky':'[Kautsky … ]',
  'irasok/osszes-proza.html#marx-szimbolizmusa':'Marx szimbolizmusa.',
  'irasok/osszes-proza.html#az-elet-I':'[Az élet …, I]',
  'irasok/osszes-proza.html#az-elet-II':'[Az élet …, II]',
  'irasok/osszes-proza.html#szep-pelda':'[Szép példa … ]',
  'irasok/osszes-proza.html#nem-szukseges-I':'[Nem szükséges … ]',
  'irasok/osszes-proza.html#azt-mondottam':'[Azt mondottam … ]',
  'irasok/osszes-proza.html#egymastol':'[ … egymástól … ]',
  'irasok/osszes-proza.html#marx':'[Marx … ]',
  'irasok/osszes-proza.html#a-nohoz-mint':'[A nőhöz, mint … ]',
  'irasok/osszes-proza.html#hegel-marx-freud-1':'Hegel – Marx – Freud',
  'irasok/osszes-proza.html#nem-volt-olyan-konyv':'[1. Nem volt olyan könyv … ]',
  'irasok/osszes-proza.html#forradalom-idejen':'[1. Forradalom idején … ]',
  'irasok/osszes-proza.html#az-animizmustol':'[Az animizmustól … ]',
  'irasok/osszes-proza.html#I-az-uj-szazad':'[I. Az uj század … ]',
  'irasok/osszes-proza.html#ekkor-azonban-elvalasztjak':'[Ekkor azonban elválasztják … ]',
  'irasok/osszes-proza.html#freudhoz':'[Freudhoz: … ]',
  'irasok/osszes-proza.html#talmat-kezzel-labbal':'[ … talmat kézzel-lábbal … ]',
  'irasok/osszes-proza.html#egyszoval':'[Egyszóval … ]',
  'irasok/osszes-proza.html#a-szemleletnek-tovabba':'[A szemléletnek továbbá … ]',
  'irasok/osszes-proza.html#puszta-fikciokhoz':'[ … puszta fikciókhoz … ]',
  'irasok/osszes-proza.html#az-irodalom-nyelvi':'[1. Az irodalom nyelvi … ]',
  'irasok/osszes-proza.html#amyennyiben-marxistak-1':'[Amennyiben marxisták … ] [1]',
  'irasok/osszes-proza.html#amyennyiben-marxistak-2':'[Amennyiben marxisták … ] [2]',
  'irasok/osszes-proza.html#amyennyiben-marxistak-3':'[Amennyiben marxisták … ] [3]',
  'irasok/osszes-proza.html#irodalom-es-szocializmus-1':'Irodalom és szocializmus [1]',
  'irasok/osszes-proza.html#irodalom-es-szocializmus-2':'Irodalom és szocializmus [2]',
  'irasok/osszes-proza.html#hajnali-madar':'Hajnali Madár.',
  'irasok/osszes-proza.html#nemzetiseg-es-gondolkodas':'Nemzetiség és gondolkodás.',
  'irasok/osszes-proza.html#mecs-laszlo-kolteszete':'Mécs László költészete',
  'irasok/osszes-proza.html#ahogy-azt-a-nagy-moricz-elkepzeli':'Ahogy azt a nagy Móricz elképzeli',
  'irasok/osszes-proza.html#tanulmanyunk-harom':'[Tanulmányunk három … ]',
  'irasok/osszes-proza.html#engels-duhring':'[Engels: Dühring … ]',
  'irasok/osszes-proza.html#a-materialistak':'[A materialisták … ]',
  'irasok/osszes-proza.html#a-dialektika-kerdesehez':'A dialektika kérdéséhez.',
  'irasok/osszes-proza.html#logika-es-dialektika':'Logika és Dialektika.',
  'irasok/osszes-proza.html#barmifele-tarsadalmi-1':'[Bármiféle társadalmi … ] [1]',
  'irasok/osszes-proza.html#barmifele-tarsadalmi-2':'[Bármiféle társadalmi … ] [2]',
  'irasok/osszes-proza.html#a-muvek-alkotoinak-es-kiadoinak':'[4. A művek alkotóinak és kiadóinak … ]',
  'irasok/osszes-proza.html#napjaink-munkasmozgalma-1':'[Napjaink munkásmozgalma … ] [1]',
  'irasok/osszes-proza.html#napjaink-munkasmozgalma-2':'[Napjaink munkásmozgalma … ] [2]',
  'irasok/osszes-proza.html#irodalom':'[Irodalom … ]',
  'irasok/osszes-proza.html#lehetseges-e-achilles':'[Lehetséges-e Achilles … ]',
  'irasok/osszes-proza.html#marxista-munkasoktatas':'Marxista munkásoktatás',
  'irasok/osszes-proza.html#kassak-lajos-35-verse':'Kassák Lajos 35 verse.',
  'irasok/osszes-proza.html#nihilizmus':'[Nihilizmus … ]',
  'irasok/osszes-proza.html#a-magyar-proletarirodalom-plattformtervezete-1':'[„A magyar proletárirodalom plattformtervezete.”]',
  'irasok/osszes-proza.html#a-magyar-proletarirodalom-plattformtervezete':'„A magyar proletárirodalom plattformtervezete.”',
  'irasok/osszes-proza.html#hegel':'[Hegel … ]',
  'irasok/osszes-proza.html#fiatalsagunk-es-a-nepmuveszet':'Fiatalságunk és a népművészet.',
  'irasok/osszes-proza.html#zsolt-bela-bellegarde':'Zsolt Béla: „Bellegarde”.',
  'irasok/osszes-proza.html#termeszettudomany-es-marxizmus':'Természettudomány és marxizmus',
  'irasok/osszes-proza.html#az-ifjusag-nemi-problemai':'Az ifjúság nemi problémái',
  'irasok/osszes-proza.html#egyeniseg-es-valosag':'Egyéniség és valóság',
  'irasok/osszes-proza.html#a-muveszet-kerdese-es-a-proletarsag':'[A müvészet kérdése és a proletárság … ]',
  'irasok/osszes-proza.html#kina':'Kina.',
  'irasok/osszes-proza.html#kapitalista-tervgazdasag-vagy-marxista-elmelet':'Kapitalista tervgazdaság vagy marxista elmélet?',
  'irasok/osszes-proza.html#emberi-eszmelet-es-tarsadalmi-haladas':'Emberi eszmélet és társadalmi haladás.',
  'irasok/osszes-proza.html#pauler-akos':'[Pauler Ákos … ]',
  'irasok/osszes-proza.html#a-nemzeti-szocializmus':'A nemzeti szocializmus',
  'irasok/osszes-proza.html#a-tortenelmi-materialista-felfogasnak':'[A történelmi materialista felfogásnak … ]',
  'irasok/osszes-proza.html#az-egysegfront-korul':'Az egységfront körül',
  'irasok/osszes-proza.html#miert-nem-en':'[Miért nem én?]',
  'irasok/osszes-proza.html#e-sorok-iroja-kolto':'[E sorok írója költő … ]',
  'irasok/osszes-proza.html#bevezetes-mely-borsot-tor':'[1. Bevezetés, mely borsot tör … ]',
  'irasok/osszes-proza.html#a-szocializmus-bolcselete':'A szocializmus bölcselete',
  'irasok/osszes-proza.html#munkanelkul-irok-tappenze':'Munkanélkül írók táppénze',
  'irasok/osszes-proza.html#o-felesegenek':'[Ő feleségének … ]',
  'irasok/osszes-proza.html#utolso-sorban':'[ … utolsó sorban … ]',
  'irasok/osszes-proza.html#reform-toborzo':'Reform-toborzó',
  'irasok/osszes-proza.html#uj-szellemi-front-2':'„Uj szellemi front”',
  'irasok/osszes-proza.html#uj-szellemi-front-1':'»Új szellemi front«',
  'irasok/osszes-proza.html#enek-a-semmirol':'Ének a semmiről',
  'irasok/osszes-proza.html#ifjusagom-elejen':'[Ifjuságom elején … ]',
  'irasok/osszes-proza.html#kosztolanyi-dezso-cikk':'Kosztolányi Dezső',
  'irasok/osszes-proza.html#babits':'[Babits … ]',
  'irasok/osszes-proza.html#rendkivul-erdekes':'[Rendkivül érdekes regényt … ]',
  'irasok/osszes-proza.html#mit-ertunk-voltakeppen-1':'[I. Mit értünk voltaképpen … ] [1]',
  'irasok/osszes-proza.html#mit-ertunk-voltakeppen-2':'[I. Mit értünk voltaképpen … ] [2]',
  'irasok/osszes-proza.html#okonomikus-realizmus-helyett':'[„Ökonomikus realizmus” helyett … ]',
  'irasok/osszes-proza.html#uj-szocializmust':'UJ SZOCIALIZMUST!',
  'irasok/osszes-proza.html#t-c':'[T. C.! … ]',
  'irasok/osszes-proza.html#azsia-lelke-1':'Ázsia lelke [1]',
  'irasok/osszes-proza.html#azsia-lelke-2':'Ázsia lelke [2]',
  'irasok/osszes-proza.html#o-lelki-kulturakra':'[Ő lelki kulturákra … ]',
  'irasok/osszes-proza.html#az-osztonokkel':'[Az ösztönökkel … ]',
  'irasok/osszes-proza.html#azsia-lelke-3':'Ázsia lelke [3]',
  'irasok/osszes-proza.html#szerkesztoi-uzenet-1':'Szerkesztői üzenet [1]',
  'irasok/osszes-proza.html#hogy-miert-nem-jarok-szinhazba':'[Hogy miért nem járok színházba? … ]',
  'irasok/osszes-proza.html#ignotus-pal-kosztolanyi-dezso':'Ignotus Pál: Kosztolányi Dezső',
  'irasok/osszes-proza.html#szerkesztoi-uzenet-2':'Szerkesztői üzenet [2]',
  'irasok/osszes-proza.html#szerkesztoi-uzenetek':'Szerkesztői üzenetek',
  'irasok/osszes-proza.html#az-uj-szellemi-fronttol-a-marciusi-frontig':'Az „Uj szellemi fronttól” a „márciusi frontig”.',
  'irasok/osszes-proza.html#erre-a-muzeumi-gyulesre':'[Erre a muzeumi gyűlésre … ]',
  'irasok/osszes-proza.html#az-eloszohoz':'[Az Előszóhoz … ]',
  'irasok/osszes-proza.html#hianyzik-egy-rovidrefogott':'[ … hiányzik egy rövidrefogott … ]',
  'irasok/osszes-proza.html#horvath-janos-magyar-versek-konyve':'Horváth János: Magyar Versek Könyve',
  'irasok/osszes-proza.html#utem-es-fogalom':'Ütem és fogalom',
  'irasok/osszes-proza.html#egyebkent-a-kovetkezo-tanulsagokat':'[Egyébként a következő tanulságokat … ]',
  'irasok/osszes-proza.html#akik-ezt-tagadjak-azok-magat-a-verset':'[Akik ezt tagadják, azok magát a verset … ]',
  'irasok/osszes-proza.html#van-e-szociologiai-indokoltsaga-az-uj-nepies-iranynak':'Van-e szociológiai indokoltsága az új népies iránynak?',
  'irasok/osszes-proza.html#a-mai-kolto-foladatai':'A mai költő föladatai',
  'irasok/osszes-proza.html#ki-a-faluba':'Ki a faluba',
  'irasok/osszes-proza.html#nagy-lajos-lecke':'Nagy Lajos: Lecke',
  'irasok/osszes-proza.html#aszlanyi-karoly-penz-a-lathataron':'Aszlányi Károly: Pénz a Láthatáron',
  'irasok/osszes-proza.html#forras-a-sivatagban':'Forrás a sivatagban – „Panorama de la Littérature Hongroise”',
  'irasok/osszes-proza.html#tisztelt-szerkesztoseg':'[Tisztelt Szerkesztőség! … ]',
  'irasok/osszes-proza.html#a-tudomany-abban-kulonbozik':'[A tudomány abban különbözik … ]',
  'irasok/osszes-proza.html#koltoi-egesz-adatos-elemzese':'Költői egész adatos elemezése.',
  'irasok/osszes-proza.html#tarsadalomelemzes-1':'Társadalomértelmezés [1]',
  'irasok/osszes-proza.html#tarsadalomelemzes-2':'Társadalomértelmezés [2]',
  'irasok/osszes-proza.html#magyarito-szotar':'Magyarító szótár.',
  'irasok/osszes-proza.html#ady-vizio':'Ady-vízió',
  'irasok/osszes-proza.html#az-idomutato-szerint':'[Az Időmutató szerint … ]',
  'irasok/osszes-proza.html#pinter-jeno-magyar-irodalomtortenete':'„Pintér Jenő Magyar Irodalomtörténete”',
  'irasok/osszes-proza.html#kulturfolenyek-haditanca':'Kultúrfőlények haditánca',
  'irasok/osszes-proza.html#doczy-jeni-arany-janos':'Dóczy Jenő: Arany János',
  'irasok/osszes-proza.html#uj-magyar-fold-es-neptelen-szavak':'Uj Magyar Föld és – néptelen szavak',
  'irasok/osszes-proza.html#bubaj-1':'Bűbáj [1]',
  'irasok/osszes-proza.html#bubaj-2':'Bűbáj [2]',
  'irasok/osszes-proza.html#az-istenek-halnak-az-ember-el':'Az Istenek halnak, az Ember él – Tárgyi kritikai tanulmány Babits Mihály verseskötetéről',
  'irasok/osszes-proza.html#magyar-mu-es-labanc-szemle':'Magyar Mü és Labanc Szemle.',
  'irasok/osszes-proza.html#a-muveszi-tenyrol':'[A müvészi tényről … ]',
  'irasok/osszes-proza.html#a-kompoziciorol-1':'A kompozicióról [1]',
  'irasok/osszes-proza.html#a-kompoziciorol-2':'A kompozicióról [2]',
  'irasok/osszes-proza.html#a-gondolkodok-1':'[A gondolkodók … ] [1]',
  'irasok/osszes-proza.html#a-gondolkodok-2':'[A gondolkodók … ] [2]',
  'irasok/osszes-proza.html#a-dolog-az-alak-es-a-nemlet-ellenteteben-valo-egyseg':'A dolog az alak és a nemlét ellentétében való egység.',
  'irasok/osszes-proza.html#semmino-dologi-let':'[Semminő dologi lét … ]',
  'irasok/osszes-proza.html#a-dolog-az-alak-es-nemlet-ellenteteben-valo-egyseg':'A dolog az alak és nemlét ellentétében való egység.',
  'irasok/osszes-proza.html#a-targy-elgondolasa':'[A tárgy elgondolása … ]',
  'irasok/osszes-proza.html#ihlet-es-nemzet':'Ihlet és nemzet',
  'irasok/osszes-proza.html#amikor-a-muveszetrol':'[Amikor a müvészetről … ]',
  'irasok/osszes-proza.html#valosag-es-igazsag':'Valóság és igazság.',
  'irasok/osszes-proza.html#muveszetrol-szolvan-1':'[Müvészetről szólván … ] [1]',
  'irasok/osszes-proza.html#muveszetrol-szolvan-2':'[Müvészetről szólván … ] [2]',
  'irasok/osszes-proza.html#az-ember':'[Az ember … ]',
  'irasok/osszes-proza.html#itt-elsosorban-es-csupan':'[Itt elsősorban és csupán … ]',
  'irasok/osszes-proza.html#hogy-cimunk-sokat-sejteto':'[Hogy címünk sokat sejtető … ]',
  'irasok/osszes-proza.html#juttathat-el-a-muveszet':'[ … juttathat el a müvészet … ]',
  'irasok/osszes-proza.html#fogalom-mig-az-ihlet':'[ … fogalom, mig az ihlet … ]',
  'irasok/osszes-proza.html#az-esztetika-eppen-ezert-nem-juttathat-el':'[ … az esztétika éppen ezért nem juttathat el … ]',
  'irasok/osszes-proza.html#igen-okosan-es-teljes-joggal':'[Igen okosan és teljes joggal … ]',
  'irasok/osszes-proza.html#a-kolteszet-nyelvben-valo':'[A költészet nyelvben való … ]',
  'irasok/osszes-proza.html#a-mualkotas-1':'[A műalkotás … ] [1]',
  'irasok/osszes-proza.html#a-mualkotas-2':'[A müalkotás … ] [2]',
  'irasok/osszes-proza.html#a-szinthetikus-itelet':'[A szinthetikus ítélet … ]',
  'irasok/osszes-proza.html#uj-szepirodalmi-folyoirat':'Uj szépirodalmi folyóirat',
  'irasok/osszes-proza.html#reti-odon-zorka':'Réti Ödön: Zorka.',
  'irasok/osszes-proza.html#delibab':'Délibáb – Terescsényi György versei',
  'irasok/osszes-proza.html#egyszeru-enekek':'Egyszerű énekek – Brichta Cézár versei',
  'irasok/osszes-proza.html#verzo-szarnyakkal':'Vérző szárnyakkal – Lőrincz Jenő versei',
  'irasok/osszes-proza.html#a-bartha-miklos-tarsasag-ertesitojehez':'A Bartha Miklós Társaság Értesítőjéhez.',
  'versek/osszes-vers.html#haromszaz-spartai-sirverse':'300 spártai sírverse',
  'versek/osszes-vers.html#munkasok-rimbaud':'Munkások',
  'versek/osszes-vers.html#meghaltak':'Meghaltak',
  'versek/osszes-vers.html#villonrol-meg-a-vastag-margotrol-szolo-ballada':'Villonról meg a vastag Margotról szóló ballada',
  'versek/osszes-vers.html#nyugasztalo-melyet-villon-szerzett':'Nyugasztaló, melyet Villon szerzett önmagáért és cimboráiért, várván, hogy vélük fölakasszák',
  'versek/osszes-vers.html#ballada-a-hajdani-idok-damairol':'Ballada a hajdani idők dámáiról',
  'versek/osszes-vers.html#ballada-melyet-villon-szerzett-edesanyja-keresere':'Ballada melyet Villon szerzett édesanyja kérésére, Szüzanyánkhoz való könyörgéseképpen',
  'versek/osszes-vers.html#villon-ferenc-nagy-testamentuma':'Villon Ferenc Nagy Testamentuma',
  'versek/osszes-vers.html#szazotven-millio':'Százötven millió',
  'versek/osszes-vers.html#idok-beteljesedese':'Idők beteljesedése',
  'versek/osszes-vers.html#tidmann-ur':'Tidmann úr',
  'versek/osszes-vers.html#ki-all-helyemre':'Ki áll helyemre?',
  'versek/osszes-vers.html#a-banyasz':'A bányász',
  'versek/osszes-vers.html#leonidas':'Leonidas',
  'versek/osszes-vers.html#katonatemeto':'Katonatemető',
  'versek/osszes-vers.html#szivem-testvere-az-ido':'Szivem testvére, az idő …',
  'versek/osszes-vers.html#konyvek-az-asztalon':'Könyvek az asztalon',
  'versek/osszes-vers.html#nyirfak':'Nyirfák',
  'versek/osszes-vers.html#del-csehorszag':'Dél-Csehország',
  'versek/osszes-vers.html#arc-az-uveg-mogott':'Arc az üveg mögött',
  'versek/osszes-vers.html#ballada-a-futo-szemeirol':'Ballada a fűtő szemeiről',
  'versek/osszes-vers.html#a-haldoklo':'A haldokló',
  'versek/osszes-vers.html#delelott-a-parkban':'Délelőtt a parkban',
  'versek/osszes-vers.html#utolso-versek':'Utolsó versek',
  'versek/osszes-vers.html#a-meszarszekek':'A mészárszékek',
  'versek/osszes-vers.html#este':'Este',
  'versek/osszes-vers.html#eros-var-a-mi-istenunk':'Erős vár a mi Istenünk',
  'versek/osszes-vers.html#egy-ember':'Egy ember …',
  'versek/osszes-vers.html#a-banyasz-aron-cotrus':'A bányász',
  'versek/osszes-vers.html#gyarban':'Gyárban',
  'versek/osszes-vers.html#ion-codru':'Ion Codru',
  'versek/osszes-vers.html#maganyos-fa':'Magányos fa',
  'versek/osszes-vers.html#hol-a-foldes-dulo':'Hol a földes, dülő …',
  'versek/osszes-vers.html#elmulas':'Elmulás',
  'versek/osszes-vers.html#oszi-ima':'Őszi ima',
  'versek/osszes-vers.html#a-tulso-part':'A tulsó part',
  'versek/osszes-vers.html#dunak':'Dünák',
  'versek/osszes-vers.html#a-golgota-kovete':'A Golgota követe',
  'versek/osszes-vers.html#ha-eljonnel':'Ha eljönnél …',
  'versek/osszes-vers.html#a-meghokkentek':'A meghökkentek',
  'versek/osszes-vers.html#ebredjetek-szolit-a-hang':'Ébredjetek, szólít a hang',
  'versek/osszes-vers.html#az-osz-az-uccan':'Az ősz az uccán',
  'versek/osszes-vers.html#tel-ion-vinea':'Tél',
  'versek/osszes-vers.html#a-sas':'A sas',
  'versek/osszes-vers.html#egyedul-vasile-ciocalteu':'Egyedül',
  'versek/osszes-vers.html#foldet-adj':'Földet adj!',
  'versek/osszes-vers.html#a-voros-lo':'A vörös ló',
  'versek/osszes-vers.html#sokasag-te':'Sokaság, te',
  'versek/osszes-vers.html#archeologia':'Archeologia',
  'versek/osszes-vers.html#aeternitas':'Aeternitas',
  'versek/osszes-vers.html#agnes':'Mese Lelle emlékére Áginak',
  'irasok/a-masodik-kolteszetbolcselet.html#a-masodik-kolteszetbolcselet':'A második költészetbölcselet',
  'irasok/besorolatlan-ketes-hitelu.html#besorolatlan-ketes-hitelu':'Besorolatlan és kétes hitelű írások',
  'irasok/hegel-marx-freud.html#hegel-marx-freud-oldal':'Hegel – Marx – Freud köré tartozó szövegek',
  'irasok/ihlet-es-nemzet.html#ihlet-es-nemzet-oldal':'Ihlet és nemzet, írások',
  'irasok/irasok-1923-28.html#irasok-1923-28':'1923—28 írásai',
  'irasok/irasok-1928-30.html#irasok-1928-30':'1928—30 írásai',
  'irasok/irasok-1930-37.html#irasok-1930-37':'1930—37 írásai',
  'irasok/irasok-1930.html#irasok-1930':'1930 írásai',
  'irasok/irodalom-es-szocializmus.html#irodalom-es-szocializmus-oldal':'Irodalom és szocializmus köré épülő szövegek',
  'irasok/szepproza.html#szepproza':'Széppróza',
  'irasok/tarsszerzo.html#tarsszerzo':'Társszerzői szöveg'
}
$(document).ready(function(){
  $("#alkeres").keyup(function(e){
    var matches = {};
    var matchesCount = 0;
    if($(this).val().length>1) {
      var test = $(this).val().toLowerCase();
      $.each(muvek,function(index,value){
        if(value.toLowerCase().match(test,'g')  && matchesCount < 10) {
          matches[index] = value;
          matchesCount++;
        }
      });
    }
    $('#talalat').html("");
    $.each(matches,function(index,value){
      $('#talalat').append("<li><a href='../"+index+"'>"+value+"</a>");
    });
  });
  alkeres.onsearch= function () { $('#talalat').html(''); };
});